import os
import re
import calendar
from functools import wraps
from datetime import datetime, date
from flask import session, request, redirect, url_for, flash, current_app
from flask_login import current_user
from .extensions import db
from .models import ActivityLog

def log_activity(action, details=None):
    """
    Helper function to log user activity.
    """
    if not current_user or not current_user.is_authenticated:
        return

    try:
        # Get IP address securely
        if request.headers.getlist("X-Forwarded-For"):
            ip = request.headers.getlist("X-Forwarded-For")[0]
        else:
            ip = request.remote_addr

        activity = ActivityLog(
            user_id=current_user.id,
            action=action,
            details=details,
            ip_address=ip
        )
        db.session.add(activity)
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        # Don't break the main flow if logging fails
        current_app.logger.error(f"Failed to log activity: {e}")

# -------------------------
# Simple i18n
# -------------------------
LANGS = ('vi', 'en')
TRANSLATIONS = {
    'vi': {
        'btn_add': 'Thêm',
        'btn_add_task': 'Thêm công việc',
        'task_created_success': 'Đã thêm công việc thành công',
        'task_updated_success': 'Cập nhật công việc thành công',
        'task_deleted_success': 'Đã xóa công việc',
        'title_edit_project': 'Sửa Dự Án',
        'nav_dashboard': 'Dashboard',
        'nav_clients': 'Clients',
        'nav_calendar': 'Lịch',
        'nav_project_list': 'Danh sách dự án',
        'nav_quotation_list': 'Danh sách báo giá',
        'nav_staff': 'Danh sách nhân viên',
        'nav_admin_users': 'Người dùng',
        'nav_backup': 'Sao lưu',
        'nav_change_password': 'Đổi mật khẩu',
        'nav_activity_report': 'Báo cáo hoạt động',
        'nav_work_history_report': 'Nhật ký',
        'nav_logout': 'Đăng xuất',
        'nav_login': 'Đăng nhập',
        'nav_language': 'Ngôn ngữ',
        'lang_vi': 'Tiếng Việt',
        'lang_en': 'English',
        'page_dashboard_title': 'Summary Dashboard',
        'btn_add_project': 'Thêm dự án',
        'btn_add_quotation': 'Thêm báo giá',
        'menu_add_project': 'Thêm dự án mới',
        'menu_add_quotation': 'Thêm dự án báo giá',
        'btn_export_report': 'Xuất báo cáo',
        'btn_view_calendar': 'Xem lịch',
        'btn_print_report_html': 'In Tổng Quan',
        'btn_print_projects': 'In Chi Tiết Dự Án',
        'summary_total_projects': 'Tổng dự án',
        'summary_completed': 'Hoàn thành',
        'summary_in_progress': 'Đang thực hiện',
        'summary_avg_progress': 'Tiến độ TB',
        'greeting_hello': 'Xin chào',
        'questions_title': 'Danh sách câu hỏi',
        'btn_add_question': 'Đặt câu hỏi',
        'no_questions': 'Không có câu hỏi nào.',
        'card_create_new': 'Tạo mới',
        'card_download': 'Tải xuống',
        'alerts_title': 'Cảnh báo',
        'btn_toggle_density': 'Chế độ gọn',
        'pagination_prev': '<< Trước',
        'pagination_next': 'Sau >>',
        'pagination_page': 'Trang',
        'pagination_of': '/',
        'no_projects': 'Chưa có dự án nào.',
        'filter_status': 'Trạng thái',
        'filter_owner': 'Employer',
        'filter_year': 'Năm',
        'filter_client': 'Khách hàng',
        'deadline_from': 'Từ ngày',
        'deadline_to': 'Đến ngày',
        'progress': 'Tiến độ',
        'btn_filter': 'Lọc',
        'btn_search': 'Tìm kiếm',
        'label_time_filter': 'Lọc nhanh theo thời gian',
        'quick_filter_placeholder': '-- Chọn nhanh --',
        'filter_today': 'Hôm nay',
        'filter_this_week': 'Tuần này',
        'view_by_entry': 'Dòng nhật ký',
        'view_by_project': 'Theo dự án',
        'col_project_name': 'Tên dự án',
        'col_code': 'Mã Dự Án',
        'col_client': 'Khách hàng',
        'col_deadline': 'Deadline',
        'col_progress': 'Tiến độ',
        'col_last_update': 'Cập nhật cuối',
        'col_assignee': 'Employer',
        'col_actions': 'Thao tác',
        'page_project_detail_title': 'Chi tiết dự án',
        'btn_back': 'Quay lại',
        'btn_export_pdf': 'Xuất PDF',
        'btn_edit': 'Sửa',
        'card_project_details': 'Chi tiết dự án',
        'label_client': 'Khách hàng',
        'label_code': 'Mã Dự Án',
        'label_address': 'Địa chỉ',
        'label_deadline': 'Deadline',
        'label_scope': 'Scope',
        'label_current_status': 'Trạng thái hiện tại',
        'label_current_progress': 'Tiến độ hiện tại',
        'label_status_progress': 'Trạng thái & Tiến độ',
        'btn_update_status_progress': 'Cập nhật Trạng thái & Tiến độ',
        'card_update_status_title': 'Cập nhật trạng thái & Tiến độ',
        'label_status': 'Trạng thái',
        'label_progress': 'Tiến độ (%)',
        'label_update_content': 'Nội dung cập nhật',
        'placeholder_update_content': 'Nhập nội dung cập nhật...',
        'btn_save_update': 'Lưu cập nhật',
        'card_tasks_title': 'Công việc',
        'task_name': 'Tên việc',
        'assignee': 'Phụ trách',
        'status': 'Trạng thái',
        'deadline': 'Deadline',
        'actions': 'Thao tác',
        'history_title': 'Lịch sử cập nhật',
        'history_time': 'Thời gian',
        'history_updated_by': 'Người cập nhật',
        'history_status': 'Trạng thái',
        'history_progress': 'Tiến độ',
        'history_detail': 'Chi tiết',
        'no_history_yet': 'Chưa có lịch sử cập nhật.',
        'title_activity_report': 'Báo cáo hoạt động',
        'title_work_history_report': 'Nhật ký',
        'page_work_history_title': 'Nhật ký công việc',
        'label_user': 'Người dùng',
        'label_all_users': 'Tất cả người dùng',
        'label_from_date': 'Từ ngày',
        'label_to_date': 'Đến ngày',
        'btn_print_report': 'In báo cáo',
        'btn_export_csv': 'Xuất CSV',
        'btn_clear_filters': 'Xóa lọc',
        'col_time': 'Thời gian',
        'col_action': 'Hành động',
        'col_details': 'Chi tiết',
        'col_ip_address': 'Địa chỉ IP',
        'activity_no_data': 'Không có dữ liệu hoạt động nào phù hợp.',
        'activity_print_generated_at': 'Báo cáo được xuất lúc',
        'activity_summary_total': 'Tổng số hoạt động',
        'activity_summary_user': 'Người dùng',
        'activity_summary_date_range': 'Khoảng thời gian',
        'activity_summary_all_users': 'Tất cả người dùng',
        'activity_summary_all_dates': 'Tất cả thời gian',
        'activity_LOGIN': 'Đăng nhập',
        'activity_LOGOUT': 'Đăng xuất',
        'activity_CREATE_PROJECT': 'Tạo dự án',
        'activity_UPDATE_PROJECT': 'Cập nhật dự án',
        'activity_DELETE_PROJECT': 'Xóa dự án',
        'activity_CREATE_CLIENT': 'Tạo khách hàng',
        'activity_UPDATE_CLIENT': 'Cập nhật khách hàng',
        'activity_DELETE_CLIENT': 'Xóa khách hàng',
        'activity_CREATE_USER': 'Tạo người dùng',
        'activity_UPDATE_USER': 'Cập nhật người dùng',
        'activity_DELETE_USER': 'Xóa người dùng',
        'activity_APPROVE_USER': 'Duyệt đăng nhập',
        'activity_CREATE_TASK': 'Tạo công việc',
        'activity_UPDATE_TASK': 'Cập nhật công việc',
        'activity_DELETE_TASK': 'Xóa công việc',
        'activity_UPDATE_TASK_STATUS': 'Cập nhật trạng thái công việc',
        'activity_CREATE_QUESTION': 'Thêm câu hỏi',
        'activity_UPDATE_QUESTION': 'Trả lời câu hỏi',
        'activity_DELETE_QUESTION': 'Xóa câu hỏi',
        'work_history_total': 'Tổng số mục',
        'work_history_add_title': 'Nhập nhật ký',
        'work_history_no_data': 'Không có dữ liệu nhật ký phù hợp.',
        'label_work_type': 'Loại công việc',
        'label_email_from': 'Người gửi email',
        'label_email_to': 'Người nhận email',
        'label_project': 'Dự án',
        'label_all_projects': 'Tất cả dự án',
        'label_work_date': 'Ngày làm',
        'label_change_details': 'Công việc đã làm trong ngày',
        'col_work_date': 'Ngày làm',
        'label_filter_options': 'Tùy chọn lọc',
        'label_search_text': 'Tìm kiếm',
        'btn_reset_filters': 'Đặt lại lọc',
        'label_scope_filter': 'Phạm vi',
        'scope_mine': 'Chỉ của tôi',
        'scope_all': 'Tất cả người tham gia',
        'placeholder_work_type': 'Ví dụ: Gửi email, họp, nộp hồ sơ...',
        'placeholder_email_from': 'Ví dụ: abc@domain.com',
        'placeholder_email_to': 'Ví dụ: xyz@domain.com, ...',
        'select_project_placeholder': '-- Chọn dự án --',
        'placeholder_change_details': 'Mô tả công việc đã làm trong ngày...',
        'btn_add_work_history': 'Lưu mục',
        'col_work_type': 'Loại công việc',
        'col_email_from': 'Người gửi email',
        'col_email_to': 'Người nhận email',
        'col_project': 'Dự án',
        'col_change_details': 'Thay đổi',
        'col_entered_by': 'Người nhập',
        'err_work_type_required': 'Vui lòng nhập loại công việc.',
        'err_email_from_required': 'Vui lòng nhập email gửi.',
        'err_email_to_required': 'Vui lòng nhập email nhận.',
        'err_project_required': 'Vui lòng chọn dự án.',
        'err_change_details_required': 'Vui lòng nhập nội dung thay đổi.',
        'err_project_not_found': 'Không tìm thấy dự án.',
        'msg_work_history_added': '✅ Đã lưu nhật ký.',
        'label_search': 'Tìm kiếm',
        'placeholder_search_journal': 'Tìm trong loại công việc, nội dung nhật ký...',
        'title_add_project': 'Thêm Dự Án Mới',
        'title_add_quotation': 'Thêm dự án báo giá',
        'label_client_field': 'Client',
        'label_client_symbol': 'Ký hiệu Client',
        'label_project_name': 'Tên dự án',
        'label_project_number': 'Project No.',
        'label_address_field': 'Địa chỉ',
        'label_deadline_field': 'Deadline',
        'label_estimated_duration': 'Thời gian dự kiến (giờ)',
        'label_scope_field': 'Phạm vi công việc / Mô tả',
        'label_update_status_action': 'Cập nhật trạng thái',
        'label_update_progress_action': 'Cập nhật tiến độ',
        'placeholder_update_status': 'Chọn trạng thái',
        'placeholder_update_progress': 'Chọn tiến độ',
        'label_owners': 'Employer (có thể chọn nhiều)',
        'label_question': 'Câu hỏi / Ghi chú',
        'title_add_question_modal': 'Thêm câu hỏi mới',
        'label_question_content': 'Nội dung câu hỏi',
        'placeholder_question': 'Nhập câu hỏi của bạn...',
        'btn_send_question': 'Gửi câu hỏi',
        'badge_unanswered': 'Chưa trả lời',
        'badge_answered': 'Đã trả lời',
        'btn_reply': 'Trả lời',
        'title_answer_modal': 'Trả lời câu hỏi',
        'label_answer_content': 'Nội dung câu trả lời',
        'btn_send_answer': 'Gửi câu trả lời',
        'col_due_date': 'Hạn chót',
        'confirm_delete_question': 'Bạn có chắc muốn xóa?',
        'err_question_empty': 'Nội dung câu hỏi không được để trống.',
        'msg_question_added': '✅ Câu hỏi đã được thêm.',
        'err_answer_empty': 'Nội dung câu trả lời không được để trống.',
        'msg_question_answered': '✅ Đã trả lời câu hỏi.',
        'err_delete_question_denied': 'Bạn không có quyền xóa câu hỏi này.',
        'msg_question_deleted': '🗑️ Câu hỏi đã được xóa.',
        'text_auto_delete': 'Tự động xóa sau:',
        'err_answer_denied': 'Bạn không đủ quyền để trả lời câu hỏi này.',
        'unknown': 'Không rõ',
        'label_source': 'Source',
        'select_client_placeholder': '-- Chọn Client --',
        'symbol_autofill_placeholder': 'Tự điền theo Client',
        'po_placeholder': '8 chữ số, ví dụ: 12345678',
        'address_placeholder': 'Ví dụ: 123 Đường ABC, Quận XYZ',
        'scope_placeholder': 'Mô tả ngắn gọn',
        'progress_placeholder': '0 - 100',
        'err_po_required': 'Vui lòng nhập Project number',
        'err_po_format': 'Project number phải gồm đúng 8 chữ số',
        'err_address_required': 'Vui lòng nhập địa chỉ',
        'err_deadline_required': 'Vui lòng chọn deadline',
        'err_deadline_past': 'Deadline không được trước hôm nay',
        'err_scope_required': 'Vui lòng mô tả phạm vi công việc',
        'initial_status': 'Trạng thái ban đầu',
        'initial_progress': 'Tiến độ ban đầu (%)',
        'btn_save_project': 'Lưu Dự Án',
        'btn_cancel': 'Hủy',
        'status_New': 'Mới',
        'status_In_Progress': 'Đang thực hiện',
        'status_Ongoing': 'Đang thực hiện',
        'status_Completed': 'Hoàn thành',
        'status_Suspended': 'Tạm dừng',
        'status_On_Hold': 'Tạm dừng',
        'status_Close': 'Đã đóng',
        'status_Quotation': 'Báo giá',
        'quotation_not_started': 'Not Started',
        'quotation_doing': 'In Progress',
        'quotation_submitted': 'Submitted',
        'quotation_quote_sent': 'Quote Sent',
        'quotation_won': 'Quotation Won',
        'NOT_STARTED': 'Chưa bắt đầu',
        'task_status_New': 'Chưa tiến hành',
        'task_status_Doing': 'Đang tiến hành',
        'task_status_Done': 'Đã hoàn thành',
        'not_started': 'Chưa tiến hành',
        'task_description': 'Mô tả công việc',
        'task_description_placeholder': 'Mô tả công việc',
        'task_list_title': 'Danh sách công việc cho dự án:',
        'task_name_placeholder': 'Tên công việc',
        'select_assignee_placeholder': '-- Người thực hiện --',
        'btn_add_task': '➕ Thêm công việc',
        'overdue': 'Quá hạn',
        'due_soon': 'Sắp đến hạn',
        'no_data': 'Không có dữ liệu.',
        'tab_files': 'Tệp',
        'tab_notes': 'Ghi chú',
        'title_project_list': 'Danh sách Dự án',
        'page_quotation_list_title': 'Danh sách Báo giá',
        'quotation_list_title': 'Danh sách Báo giá',
        'title_edit_history': 'Sửa lịch sử',
        'confirm_delete_user': 'Xóa user này?',
        'label_new_status': 'Trạng thái mới',
        'label_new_progress': 'Tiến độ mới (%)',
        'label_detail': 'Chi tiết',
        'unassigned': 'Chưa phân công',
        'not_available': 'N/A',
        'confirm_delete_task': 'Xóa công việc này?',
        'no_update': 'Chưa cập nhật',
        'confirm_delete_project': 'Bạn có chắc chắn muốn xóa dự án này không? Hành động này không thể hoàn tác.',
        'label_time_est_short': 'Thời gian dự kiến',
        'label_time_spent_short': 'Thời gian đã dùng',
        'label_time_remain_short': 'Thời gian còn lại',
        'col_time_est_spent': 'Thời gian dự kiến',
        'title_clients': 'Danh sách Client',
        'title_add_client': 'Thêm Client',
        'title_edit_client': 'Sửa Client',
        'label_note': 'Ghi chú',
        'btn_add_client': 'Thêm Client',
        'col_index': 'STT',
        'col_client_name': 'Tên Client',
        'col_symbol': 'Ký hiệu',
        'col_color': 'Màu sắc',
        'title_choose_color': 'Chọn màu nhận diện',
        'modal_delete_client_title': 'Xác nhận xóa Client',
        'modal_delete_client_body': 'Xác nhận xóa client "{name}"? Hành động này không thể hoàn tác.',
        'modal_delete_user_body': 'Xác nhận xóa người dùng "{name}"? Hành động này không thể hoàn tác.',
        'btn_delete': 'Xóa',
        'btn_cancel_text': 'Hủy',
        'empty_clients': 'Chưa có Client nào.',
        'title_admin_users': 'Quản trị Người dùng',
        'btn_back_clients': 'Quay lại Clients',
        'btn_back_dashboard': 'Dashboard',
        'placeholder_email': 'Email (username)',
        'placeholder_display_name': 'Tên hiển thị',
        'label_role': 'Vai trò',
        'label_password': 'Mật khẩu',
        'label_confirm': 'Xác nhận',
        'label_allowed_login': 'Cho phép đăng nhập',
        'btn_add_user': 'Thêm người dùng',
        'status_allowed': 'Được phép',
        'status_blocked': 'Bị chặn',
        'btn_update': 'Cập nhật',
        'empty_users': 'Chưa có người dùng nào.',
        'title_login': 'Đăng nhập',
        'heading_login': 'Đăng nhập hệ thống',
        'label_email_username': 'Email / Username',
        'btn_login': 'Đăng nhập',
        'footer_text': '© 2025 FG Consulting Engineers — Project management system',
        'title_change_password': 'Đổi mật khẩu',
        'label_current_password': 'Mật khẩu hiện tại',
        'label_new_password': 'Mật khẩu mới',
        'label_confirm_password': 'Xác nhận mật khẩu mới',
        'btn_save': 'Lưu',
        'title_backup': 'Quản lý sao lưu',
        'heading_backup': 'Quản lý sao lưu dữ liệu',
        'btn_create_backup': 'Tạo bản sao lưu mới',
        'btn_upload_backup': 'Tải lên bản sao lưu',
        'col_filename': 'Tên file',
        'col_created': 'Ngày tạo',
        'btn_view_all': 'Xem tất cả',
        'title_all_questions': 'Tất cả câu hỏi',
        'col_size': 'Kích thước',
        'btn_download': 'Tải xuống',
        'btn_restore': 'Phục hồi',
        'btn_delete': 'Xóa',
        'empty_backups': 'Chưa có bản sao lưu nào.',
        'summary_total_backups': 'Tổng số bản sao lưu',
        'summary_total_size': 'Tổng dung lượng',
        'summary_last_backup': 'Sao lưu gần nhất',
        'modal_upload_title': 'Tải lên bản sao lưu',
        'modal_restore_title': 'Xác nhận phục hồi',
        'modal_restore_body': 'Bạn có chắc chắn muốn phục hồi dữ liệu từ bản sao lưu này? Dữ liệu hiện tại sẽ bị thay thế!',
        'modal_delete_title': 'Xác nhận xóa',
        'modal_delete_body': 'Bạn có chắc chắn muốn xóa bản sao lưu này không?',
        'msg_upload_success': 'Tải lên bản sao lưu thành công.',
        'msg_upload_failed': 'Tải lên thất bại.',
        'msg_invalid_file': 'File không hợp lệ.',
        'report_summary': 'Tóm tắt báo cáo',
        'report_total_projects': 'Tổng số dự án',
        'report_total_clients': 'Tổng khách hàng',
        'report_completed': 'Hoàn thành',
        'report_avg_progress': 'Tiến độ trung bình',
        'report_overdue': 'Quá hạn',
        'report_unassigned': 'Chưa phân công',
        'report_client': 'Client',
        'report_project_overview': 'PROJECT OVERVIEW REPORT',
        'report_generated_by': 'Report generated by FG Consulting Engineers Project Management System',
        'report_generated_at': 'Generated at',
        'title_reports': 'KPI Reports',
        'heading_reports_client_kpi': 'Báo cáo KPI theo Client',
        'tasks_incomplete': 'Công việc chưa hoàn thành',
        'no_tasks': 'Chưa có công việc nào.',
        'msg_access_denied': 'Không có quyền truy cập',
        'btn_prev': 'trước',
        'btn_next': 'sau',
        'msg_select_project_to_print': 'Vui lòng chọn dự án để in.',
        'label_project_type': 'Loại dự án',
        'type_fgc_title': 'FGC Project',
        'type_pei_title': 'PEI Project',
        'section_identity': 'Thông tin định danh',
        'section_details_timeline': 'Chi tiết & Thời gian',
        'msg_auto_title_case': 'Hệ thống sẽ tự động viết hoa chữ cái đầu mỗi từ (Title Case).',
        'msg_fill_info_add': 'Điền thông tin chi tiết để khởi tạo dự án mới',
        'msg_fill_info_edit': 'Điền thông tin chi tiết để cập nhật dự án hiện tại',
        'placeholder_project_name': 'Nhập tên dự án...',
        'placeholder_auto': 'Tự động',
        'msg_confirm_change_po': 'Bạn đang thay đổi Project Number, bạn có muốn tiếp tục không?',
        'msg_po_exists': 'Project number này đã tồn tại cho client đã chọn (và người phụ trách nếu có). Vui lòng nhập số khác.',
        'section_team_status': 'Nhân sự & Trạng thái',
        'msg_multi_select_instruction': 'Giữ phím Ctrl (Windows) hoặc Command (Mac) để chọn nhiều người.',
        'msg_fill_info_add_client': 'Điền thông tin để thêm khách hàng mới',
        'msg_fill_info_edit_client': 'Điền thông tin để cập nhật khách hàng',
        'placeholder_client_name': 'Nhập tên khách hàng...',
        'placeholder_client_symbol': 'Ví dụ: F1, ABC...',
        'placeholder_note': 'Ghi chú (tùy chọn)...',
        'msg_auto_uppercase': 'Hệ thống sẽ tự động viết hoa toàn bộ (UPPERCASE).',
        'client_added_success': '✅ Client đã được thêm.',
        'client_updated_success': '✅ Client đã được cập nhật.',
        'client_deleted_success': '🗑️ Client "{name}" đã được xóa.',
        'err_client_exists': 'Client đã tồn tại (tên hoặc ký hiệu trùng).',
        'err_name_symbol_required': 'Vui lòng nhập tên và ký hiệu.',
        'col_projects_count': 'Số lượng dự án',
        'placeholder_search_clients': 'Tìm kiếm khách hàng...',
        'tooltip_edit': 'Chỉnh sửa',
        'tooltip_delete': 'Xóa',
        'title_calendar_page': 'Lịch dự án',
        'filter_all_clients': '-- Tất cả Khách hàng --',
        'filter_all_statuses': '-- Tất cả Trạng thái --',
        'legend_title': 'Chú thích:',
        'legend_in_progress': 'Đang thực hiện',
        'legend_completed': 'Hoàn thành',
        'legend_close': 'Đã đóng',
        'legend_suspended': 'Tạm dừng',
        'legend_other': 'Khác/Quá hạn',
        'calendar_list': 'Danh sách',
        'calendar_year': 'Năm',
        'calendar_month': 'Tháng',
        'calendar_week': 'Tuần',
        'subtitle_admin_users': 'Quản lý tài khoản và phân quyền hệ thống',
        'placeholder_search_users': 'Tìm kiếm tên, email...',
        'filter_all_roles': '-- Tất cả vai trò --',
        'col_account_info': 'Thông tin tài khoản',
        'col_role': 'Vai trò',
        'col_status': 'Trạng thái',
        'col_actions': 'Thao tác',
        'status_active': 'Hoạt động',
        'status_locked': 'Đã khóa',
        'btn_edit_info': 'Sửa thông tin',
        'title_add_user_modal': 'Thêm người dùng mới',
        'label_username': 'Username',
        'label_email': 'Email',
        'label_display_name': 'Tên hiển thị',
        'label_role': 'Vai trò',
        'label_password': 'Mật khẩu',
        'label_confirm_password': 'Xác nhận mật khẩu mới',
        'label_allow_login_now': 'Cho phép đăng nhập ngay',
        'btn_add_user_confirm': 'Thêm người dùng',
        'title_edit_user_modal': 'Cập nhật thông tin',
        'label_new_password_optional': 'Mật khẩu mới',
        'text_optional_password': '(để trống nếu không đổi)',
        'placeholder_new_password': 'Nhập mật khẩu mới...',
        'label_allow_login': 'Cho phép đăng nhập',
        'btn_save_changes': 'Lưu thay đổi',
        'modal_date_options_title': 'Tùy chọn cho ngày {date}',
        'btn_add_project_here': 'Thêm dự án tại đây',
        'btn_add_note': 'Thêm ghi chú',
        'placeholder_note_content': 'Nhập nội dung ghi chú...',
        'confirm_delete_note': 'Xóa ghi chú này?',
        'note_saved': 'Đã lưu ghi chú!',
        'type_note': 'Ghi chú',
        'type_appointment': 'Lịch hẹn',
        'label_note_type': 'Loại',
        'notification_title': 'Thông báo',
        'notification_today': 'Hôm nay',
        'notification_upcoming': 'Sắp tới',
        'no_notifications': 'Không có thông báo mới',
        'title_edit_note_modal': 'Chi tiết Ghi chú / Lịch hẹn',
        'btn_update_note': 'Cập nhật',
        'btn_delete_note': 'Xóa',
        'btn_close': 'Đóng',
        'dashboard': 'Bảng điều khiển',
        'btn_print_report_html': 'In Tổng Quan',
        'btn_print_browser': 'In (Trình duyệt)',
        'btn_download_pdf': 'Tải PDF',
        'btn_view_details': 'Xem',
        'confirm_delete': 'Bạn có chắc chắn muốn xóa không?',
        'pagination_showing': 'Đang hiển thị',
        'card_questions': 'Câu hỏi dự án',
        'label_group_by': 'Chế độ in',
        'group_by_client': 'Theo Khách hàng',
        'group_by_owner': 'Theo Employer',
        'group_by_status': 'Theo Trạng thái',
        'group_by_type': 'Theo Loại Dự án',
        'type_FGC': 'Dự án FGC',
        'type_PEI': 'Dự án PEI',
        'report_generated_by': 'Người xuất',
        'label_view_by': 'Xem theo',
        'label_time_filter': 'Lọc thời gian',
        'quick_filter_placeholder': '-- Chọn nhanh --',
        'filter_this_month': 'Tháng này',
        'filter_last_month': 'Tháng trước',
        'filter_this_year': 'Năm nay',
        'filter_last_year': 'Năm ngoái',
        'btn_print_browser_action': 'In (Trình duyệt)',
        'dashboard_status_overview': 'Tổng quan trạng thái',
        'search_placeholder': 'Tìm tên dự án, mã dự án, địa điểm...',
        'filter_all_owners': '-- Tất cả Employer --',
        'filter_reset_title': 'Đặt lại bộ lọc',
        'toggle_dark_mode': 'Chế độ tối',
        'search_label': 'Tìm kiếm',
        'msg_login_required': '❌ Bạn cần đăng nhập.',
        'msg_no_permission': '❌ Không có quyền.',
        'err_fill_all_fields': 'Vui lòng điền đủ thông tin.',
        'err_email_format': 'Định dạng email không hợp lệ.',
        'err_password_strength': 'Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt.',
        'err_password_mismatch': 'Mật khẩu và xác nhận không khớp.',
        'err_manager_create_admin': 'Manager không thể tạo tài khoản Admin.',
        'msg_user_added': '✅ Đã thêm người dùng.',
        'err_user_exists': '❌ Username hoặc Email đã tồn tại.',
        'err_user_add_failed': '❌ Lỗi khi thêm người dùng.',
        'err_user_not_found': 'Không tìm thấy người dùng.',
        'err_manager_edit_admin': 'Manager không thể chỉnh sửa tài khoản Admin.',
        'err_email_required': 'Email không được để trống.',
        'err_email_used': 'Email này đã được sử dụng bởi tài khoản khác.',
        'err_manager_promote_admin': 'Manager không thể cấp quyền Admin.',
        'err_password_change_denied': 'Bạn không có quyền đổi mật khẩu cho người dùng này.',
        'msg_password_updated': '✅ Đã cập nhật mật khẩu mới.',
        'msg_user_updated': '✅ Đã cập nhật người dùng.',
        'err_user_update_failed': '❌ Lỗi khi cập nhật người dùng.',
        'err_delete_self': '❌ Không thể xoá tài khoản hiện tại.',
        'err_manager_delete_admin': 'Manager không thể xóa tài khoản Admin.',
        'msg_user_deleted': '🗑️ Đã xoá người dùng.',
        'err_user_delete_failed': '❌ Lỗi khi xoá người dùng.',
        'msg_login_allowed': '✅ Đã cho phép đăng nhập.',
        'err_login_status_update_failed': '❌ Lỗi khi cập nhật trạng thái đăng nhập.',
        'err_login_not_allowed': '❌ Tài khoản chưa được phép đăng nhập.',
        'msg_login_success': '✅ Đăng nhập thành công!',
        'err_login_failed': '❌ Sai tài khoản hoặc mật khẩu.',
        'err_login_error': '❌ Lỗi đăng nhập. Vui lòng thử lại.',
        'msg_logout_success': '🚪 Đã đăng xuất.',
        'err_current_password_incorrect': 'Mật khẩu hiện tại không đúng.',
        'msg_password_change_success': '✅ Đổi mật khẩu thành công.',
        'msg_backup_created': '✅ Đã tạo backup: ',
        'err_backup_failed': '❌ Tạo backup thất bại.',
        'msg_restore_success': '♻️ Phục hồi thành công. Khởi động lại ứng dụng.',
        'err_restore_failed': '❌ Phục hồi thất bại.',
        'msg_backup_deleted': '🗑️ Đã xóa backup.',
        'err_backup_delete_failed': '❌ Xóa backup thất bại.',
        'report_project_detail_title': 'PROJECT DETAIL REPORT',
        'report_combined_title': 'COMBINED PROJECT REPORT',
        'err_invalid_ids_list': 'Danh sách ids không hợp lệ',
        'err_ids_must_be_int': 'IDs phải là số nguyên',
        'err_projects_not_found': 'Không tìm thấy dự án',
        'err_no_project_selected': 'Không có dự án nào được chọn',
        'err_export_pdf_failed': 'Xuất PDF thất bại',
        'err_path_not_exists': 'Đường dẫn không tồn tại!',
        'msg_folder_opened': 'Đã mở thư mục.',
        'err_open_folder_failed': 'Không thể mở thư mục: ',
        'label_time_est_short': 'Thời gian dự kiến',
        'label_time_spent_short': 'Đã làm',
        'label_time_remain_short': 'Còn lại',
        'col_time_est_spent': 'Th.gian (Dự kiến/Đã làm)',
        'alert_connection_error': 'Lỗi kết nối',
        'alert_enter_task_content': 'Vui lòng nhập nội dung công việc!',
        'alert_update_failed': 'Cập nhật thất bại',
        'kanban_doing': 'Đang làm',
        'kanban_done': 'Hoàn thành',
        'kanban_new': 'Mới',
        'kanban_subtitle': 'Kéo thả để cập nhật trạng thái',
        'kanban_title': 'Kanban',
        'btn_print_this_page': 'In trang này',
    },
    'en': {
        'btn_add': 'Add',
        'btn_add_task': 'Add Task',
        'task_created_success': 'Task added successfully',
        'task_updated_success': 'Task updated successfully',
        'task_deleted_success': 'Task deleted successfully',
        'title_edit_project': 'Edit Project',
        'nav_dashboard': 'Dashboard',
        'nav_clients': 'Clients',
        'nav_calendar': 'Calendar',
        'nav_project_list': 'Projects',
        'nav_quotation_list': 'Quotations',
        'nav_staff': 'Staff List',
        'nav_admin_users': 'Users',
        'nav_backup': 'Backup',
        'nav_change_password': 'Change Password',
        'nav_activity_report': 'Activity Log',
        'nav_work_history_report': 'Work History',
        'nav_logout': 'Logout',
        'nav_login': 'Login',
        'nav_language': 'Language',
        'lang_vi': 'Tiếng Việt',
        'lang_en': 'English',
        'page_dashboard_title': 'Summary Dashboard',
        'btn_add_project': 'Add Project',
        'btn_add_quotation': 'Add Quotation Project',
        'menu_add_project': 'Add New Project',
        'menu_add_quotation': 'Add Quotation Project',
        'btn_export_report': 'Export Report',
        'btn_view_calendar': 'View Calendar',
        'btn_print_projects': 'Print Projects',
        'label_group_by': 'Print Mode',
        'group_by_client': 'By Client',
        'group_by_owner': 'By Employer',
        'group_by_status': 'By Status',
        'group_by_type': 'By Project Type',
        'type_FGC': 'FGC Projects',
        'type_PEI': 'PEI Projects',
        'card_questions': 'Project Questions',
        'summary_total_projects': 'Total Projects',
        'summary_completed': 'Completed',
        'summary_in_progress': 'In Progress',
        'summary_avg_progress': 'Avg Progress',
        'greeting_hello': 'Hello',
        'questions_title': 'Questions List',
        'btn_add_question': 'Ask Question',
        'no_questions': 'No questions found.',
        'card_create_new': 'Create New',
        'card_download': 'Download',
        'alerts_title': 'Alerts',
        'btn_toggle_density': 'Compact Rows',
        'pagination_prev': '« Prev',
        'pagination_next': 'Next »',
        'pagination_page': 'Page',
        'pagination_of': '/',
        'no_projects': 'No projects yet.',
        'filter_status': 'Status',
        'filter_owner': 'Employer',
        'filter_year': 'Year',
        'filter_client': 'Client',
        'deadline_from': 'From date',
        'deadline_to': 'To date',
        'progress': 'Progress',
        'btn_filter': 'Filter',
        'view_by_entry': 'Entries',
        'view_by_project': 'By Project',
        'col_project_name': 'Project Name',
        'col_code': 'Project No.',
        'col_client': 'Client',
        'col_deadline': 'Deadline',
        'col_progress': 'Progress',
        'col_last_update': 'Last Update',
        'col_actions': 'Actions',
        'page_project_detail_title': 'Project Detail',
        'btn_back': 'Back',
        'btn_export_pdf': 'Export PDF',
        'btn_edit': 'Edit',
        'card_project_details': 'Project Details',
        'label_client': 'Client',
        'label_code': 'Project No.',
        'label_address': 'Address',
        'label_deadline': 'Deadline',
        'label_scope': 'Scope',
        'label_current_status': 'Current Status',
        'label_current_progress': 'Current Progress',
        'label_status_progress': 'Status & Progress',
        'btn_update_status_progress': 'Update Status & Progress',
        'card_update_status_title': 'Update Status & Progress',
        'label_status': 'Status',
        'label_progress': 'Progress (%)',
        'label_update_content': 'Update Content',
        'placeholder_update_content': 'Enter update content...',
        'btn_save_update': 'Save Update',
        'card_tasks_title': 'Tasks',
        'task_name': 'Task Name',
        'assignee': 'Assignee',
        'status': 'Status',
        'deadline': 'Deadline',
        'actions': 'Actions',
        'history_title': 'Update History',
        'history_time': 'Time',
        'history_updated_by': 'Updated By',
        'history_status': 'Status',
        'history_progress': 'Progress',
        'history_detail': 'Detail',
        'no_history_yet': 'No history yet.',
        'title_activity_report': 'Activity Report',
        'title_work_history_report': 'Journal',
        'page_work_history_title': 'Work History Journal',
        'label_user': 'User',
        'label_all_users': 'All users',
        'label_from_date': 'From date',
        'label_to_date': 'To date',
        'btn_print_report': 'Print report',
        'btn_export_csv': 'Export CSV',
        'btn_clear_filters': 'Clear filters',
        'col_time': 'Time',
        'col_action': 'Action',
        'col_details': 'Details',
        'col_ip_address': 'IP Address',
        'activity_no_data': 'No matching activity logs.',
        'activity_print_generated_at': 'Report generated at',
        'activity_summary_total': 'Total activities',
        'activity_summary_user': 'User',
        'label_time_est_short': 'Estimated Time',
        'label_time_spent_short': 'Spent',
        'label_time_remain_short': 'Remain',
        'col_time_est_spent': 'Time Est.',
        'activity_summary_date_range': 'Date range',
        'activity_summary_all_users': 'All users',
        'activity_summary_all_dates': 'All time',
        'activity_LOGIN': 'Login',
        'activity_LOGOUT': 'Logout',
        'activity_CREATE_PROJECT': 'Create project',
        'activity_UPDATE_PROJECT': 'Update project',
        'activity_DELETE_PROJECT': 'Delete project',
        'activity_CREATE_CLIENT': 'Create client',
        'activity_UPDATE_CLIENT': 'Update client',
        'activity_DELETE_CLIENT': 'Delete client',
        'activity_CREATE_USER': 'Create user',
        'activity_UPDATE_USER': 'Update user',
        'activity_DELETE_USER': 'Delete user',
        'activity_APPROVE_USER': 'Approve login',
        'activity_CREATE_TASK': 'Create task',
        'activity_UPDATE_TASK': 'Update task',
        'activity_DELETE_TASK': 'Delete task',
        'activity_UPDATE_TASK_STATUS': 'Update task status',
        'activity_CREATE_QUESTION': 'Create question',
        'activity_UPDATE_QUESTION': 'Answer question',
        'activity_DELETE_QUESTION': 'Delete question',
        'work_history_total': 'Total entries',
        'work_history_add_title': 'Add journal entry',
        'work_history_no_data': 'No matching journal entries.',
        'label_work_type': 'Work type',
        'label_email_from': 'Email from',
        'label_email_to': 'Email to',
        'label_project': 'Project',
        'label_all_projects': 'All projects',
        'label_work_date': 'Work date',
        'label_change_details': 'Work done today',
        'col_work_date': 'Work date',
        'label_filter_options': 'Filter Options',
        'label_search_text': 'Search',
        'btn_reset_filters': 'Reset Filters',
        'label_scope_filter': 'Scope',
        'scope_mine': 'My entries',
        'scope_all': 'All participants',
        'placeholder_work_type': 'e.g., Email, meeting, submission...',
        'placeholder_email_from': 'e.g., abc@domain.com',
        'placeholder_email_to': 'e.g., xyz@domain.com, ...',
        'select_project_placeholder': '-- Select project --',
        'placeholder_change_details': 'Describe the work done today...',
        'btn_add_work_history': 'Save entry',
        'col_work_type': 'Work type',
        'col_email_from': 'Email from',
        'col_email_to': 'Email to',
        'col_project': 'Project',
        'col_change_details': 'Changes',
        'col_entered_by': 'Entered by',
        'err_work_type_required': 'Please enter work type.',
        'err_email_from_required': 'Please enter sender email.',
        'err_email_to_required': 'Please enter recipient email.',
        'err_project_required': 'Please select project.',
        'err_change_details_required': 'Please enter change details.',
        'err_project_not_found': 'Project not found.',
        'msg_work_history_added': '✅ Journal entry saved.',
        'title_add_project': 'Add New Project',
        'title_add_quotation': 'Add Quotation Project',
        'label_client_field': 'Client',
        'label_client_symbol': 'Client Symbol',
        'label_project_name': 'Project Name',
        'label_project_number': 'Project No.',
        'label_address_field': 'Address',
        'label_deadline_field': 'Deadline',
        'label_estimated_duration': 'Estimated Duration (hours)',
        'label_scope_field': 'Scope / Description',
        'label_update_status_action': 'Update Status',
        'label_update_progress_action': 'Update Progress',
        'placeholder_update_status': 'Select Status',
        'placeholder_update_progress': 'Select Progress',
        'label_owners': 'Employers (multi-select)',
        'label_question': 'Question / Note',
        'title_add_question_modal': 'Ask New Question',
        'title_answer_modal': 'Answer Question',
        'label_question_content': 'Question Content',
        'placeholder_question': 'Enter your question...',
        'label_answer_content': 'Answer Content',
        'btn_send_question': 'Send Question',
        'btn_send_answer': 'Send Answer',
        'badge_unanswered': 'Unanswered',
        'badge_answered': 'Answered',
        'btn_reply': 'Reply',
        'text_auto_delete': 'Auto delete at',
        'confirm_delete_question': 'Are you sure you want to delete?',
        'err_delete_question_denied': 'You do not have permission to delete this question.',
        'err_answer_denied': 'You do not have permission to answer this question.',
        'label_source': 'Source',
        'select_client_placeholder': '-- Select Client --',
        'symbol_autofill_placeholder': 'Auto-filled from Client',
        'po_placeholder': '8 digits, e.g., 12345678',
        'address_placeholder': 'e.g., 123 ABC Street, District XYZ',
        'scope_placeholder': 'Short description',
        'progress_placeholder': '0 - 100',
        'err_po_required': 'Please enter Project number',
        'err_po_format': 'Project number must be exactly 8 digits',
        'err_address_required': 'Please enter address',
        'err_deadline_required': 'Please select deadline',
        'err_deadline_past': 'Deadline cannot be before today',
        'err_scope_required': 'Please describe the scope of work',
        'initial_status': 'Initial Status',
        'initial_progress': 'Initial Progress (%)',
        'btn_save_project': 'Save Project',
        'btn_cancel': 'Cancel',
        'status_New': 'New',
        'status_In_Progress': 'In Progress',
        'status_Completed': 'Completed',
        'status_Close': 'Closed',
        'status_On_Hold': 'On Hold',
        'status_Quotation': 'Quotation',
        'quotation_not_started': 'Not Started',
        'quotation_doing': 'In Progress',
        'quotation_submitted': 'Submitted',
        'quotation_quote_sent': 'Quote Sent',
        'quotation_won': 'Quotation Won',
        'NOT_STARTED': 'Not Started',
        'task_status_New': 'Pending',
        'task_status_Doing': 'In Progress',
        'task_status_Done': 'Completed',
        'not_started': 'Not started',
        'task_description': 'Task Description',
        'task_description_placeholder': 'Task description',
        'task_list_title': 'Task list for project:',
        'task_name_placeholder': 'Task name',
        'select_assignee_placeholder': '-- Assignee --',
        'btn_add_task': 'Add task',
        'overdue': 'Overdue',
        'due_soon': 'Due soon',
        'no_data': 'No data.',
        'tab_files': 'Files',
        'tab_notes': 'Notes',
        'title_project_list': 'Project List',
        'page_quotation_list_title': 'Quotation List',
        'quotation_list_title': 'Quotations',
        'title_edit_history': 'Edit history',
        'confirm_delete_user': 'Delete this user?',
        'label_new_status': 'New status',
        'label_new_progress': 'New progress (%)',
        'label_detail': 'Detail',
        'unassigned': 'Unassigned',
        'not_available': 'N/A',
        'confirm_delete_task': 'Delete this task?',
        'no_update': 'No update',
        'title_clients': 'Clients List',
        'title_add_client': 'Add Client',
        'title_edit_client': 'Edit Client',
        'label_note': 'Note',
        'btn_add_client': 'Add Client',
        'col_index': '#',
        'col_client_name': 'Client Name',
        'col_symbol': 'Symbol',
        'col_color': 'Color',
        'title_choose_color': 'Choose color',
        'modal_delete_client_title': 'Confirm Delete Client',
        'modal_delete_client_body': 'Confirm delete client "{name}"? This action cannot be undone.',
        'modal_delete_user_body': 'Confirm delete user "{name}"? This action cannot be undone.',
        'btn_delete': 'Delete',
        'btn_cancel_text': 'Cancel',
        'empty_clients': 'No clients yet.',
        'title_admin_users': 'User Administration',
        'btn_back_clients': 'Back to Clients',
        'placeholder_email': 'Email (username)',
        'placeholder_display_name': 'Display name',
        'label_role': 'Role',
        'label_password': 'Password',
        'label_confirm': 'Confirm',
        'label_allowed_login': 'Allow login',
        'btn_add_user': 'Add user',
        'status_allowed': 'Allowed',
        'status_blocked': 'Blocked',
        'btn_update': 'Update',
        'empty_users': 'No users yet.',
        'title_login': 'Login',
        'heading_login': 'System Login',
        'label_email_username': 'Email / Username',
        'btn_login': 'Login',
        'footer_text': '© 2025 FG Consulting Engineers — Project management system',
        'title_change_password': 'Change password',
        'label_current_password': 'Current password',
        'label_new_password': 'New password',
        'label_confirm_password': 'Confirm new password',
        'btn_save': 'Save',
        'title_backup': 'Backup Management',
        'heading_backup': 'Data Backup Management',
        'btn_create_backup': 'Create new backup',
        'btn_upload_backup': 'Upload backup',
        'col_filename': 'Filename',
        'col_created': 'Created',
        'col_size': 'Size',
        'btn_download': 'Download',
        'btn_restore': 'Restore',
        'btn_delete': 'Delete',
        'empty_backups': 'No backups yet.',
        'summary_total_backups': 'Total Backups',
        'summary_total_size': 'Total Size',
        'summary_last_backup': 'Last Backup',
        'modal_upload_title': 'Upload Backup',
        'modal_restore_title': 'Confirm Restore',
        'modal_restore_body': 'Are you sure you want to restore from this backup? Current data will be replaced!',
        'modal_delete_title': 'Confirm Delete',
        'modal_delete_body': 'Are you sure you want to delete this backup?',
        'msg_upload_success': 'Backup uploaded successfully.',
        'msg_upload_failed': 'Upload failed.',
        'msg_invalid_file': 'Invalid file.',
        'report_summary': 'Summary',
        'report_total_projects': 'Total Projects',
        'report_total_clients': 'Total Clients',
        'report_completed': 'Completed',
        'report_avg_progress': 'Average Progress',
        'report_overdue': 'Overdue',
        'report_client': 'Client',
        'report_project_overview': 'PROJECT OVERVIEW REPORT',
        'report_generated_by': 'Report generated by FG Consulting Engineers Project Management System',
        'report_generated_at': 'Generated at',
        'title_reports': 'KPI Reports',
        'heading_reports_client_kpi': 'KPI report by Client',
        'tasks_incomplete': 'Incomplete tasks',
        'no_tasks': 'No tasks yet.',
        'confirm_delete_project': 'Are you sure you want to delete this project? This action cannot be undone.',
        'msg_access_denied': 'Access denied',
        'btn_prev': 'prev',
        'btn_next': 'next',
        'msg_select_project_to_print': 'Please select projects to print.',
        'label_project_type': 'Project Type',
        'type_fgc_title': 'FGC Project',
        'type_pei_title': 'PEI Project',
        'section_identity': 'Identity Information',
        'section_details_timeline': 'Details & Timeline',
        'msg_auto_title_case': 'The system will automatically capitalize the first letter of each word (Title Case).',
        'msg_fill_info_add': 'Fill in details to create a new project',
        'msg_fill_info_edit': 'Fill in details to update the current project',
        'placeholder_project_name': 'Enter project name...',
        'placeholder_auto': 'Auto',
        'msg_confirm_change_po': 'You are changing the Project Number, do you want to continue?',
        'msg_po_exists': 'This Project Number already exists for the selected client. Please enter a different number.',
        'section_team_status': 'Team & Status',
        'msg_multi_select_instruction': 'Hold Ctrl (Windows) or Command (Mac) to select multiple people.',
        'msg_fill_info_add_client': 'Fill in details to add a new client',
        'msg_fill_info_edit_client': 'Fill in details to update client',
        'placeholder_client_name': 'Enter client name...',
        'placeholder_client_symbol': 'e.g., F1, ABC...',
        'placeholder_note': 'Note (optional)...',
        'msg_auto_uppercase': 'The system will automatically convert to UPPERCASE.',
        'client_added_success': '✅ Client added successfully.',
        'client_updated_success': '✅ Client updated successfully.',
        'client_deleted_success': '🗑️ Client "{name}" deleted successfully.',
        'err_client_exists': 'Client already exists (duplicate name or symbol).',
        'err_name_symbol_required': 'Please enter name and symbol.',
        'col_projects_count': 'Total Projects',
        'placeholder_search_clients': 'Search clients...',
        'tooltip_edit': 'Edit',
        'tooltip_delete': 'Delete',
        'title_calendar_page': 'Project Calendar',
        'filter_all_clients': '-- All Clients --',
        'filter_all_statuses': '-- All Statuses --',
        'legend_title': 'Legend:',
        'legend_in_progress': 'In Progress',
        'legend_completed': 'Completed',
        'legend_close': 'Closed',
        'legend_suspended': 'On Hold',
        'legend_other': 'Other/Overdue',
        'calendar_list': 'List',
        'calendar_year': 'Year',
        'calendar_month': 'Month',
        'calendar_week': 'Week',
        'subtitle_admin_users': 'Manage accounts and system permissions',
        'placeholder_search_users': 'Search name, email...',
        'filter_all_roles': '-- All roles --',
        'col_account_info': 'Account Info',
        'col_role': 'Role',
        'col_status': 'Status',
        'col_actions': 'Actions',
        'status_active': 'Active',
        'status_locked': 'Locked',
        'btn_edit_info': 'Edit Info',
        'title_add_user_modal': 'Add New User',
        'label_username': 'Username',
        'label_email': 'Email',
        'label_display_name': 'Display Name',
        'label_role': 'Role',
        'label_password': 'Password',
        'label_confirm_password': 'Confirm Password',
        'label_allow_login_now': 'Allow login now',
        'btn_add_user_confirm': 'Add User',
        'title_edit_user_modal': 'Update Information',
        'label_new_password_optional': 'New Password',
        'text_optional_password': '(leave blank if unchanged)',
        'placeholder_new_password': 'Enter new password...',
        'label_allow_login': 'Allow Login',
        'btn_save_changes': 'Save Changes',
        'modal_date_options_title': 'Options for {date}',
        'btn_add_project_here': 'Add Project Here',
        'btn_add_note': 'Add Note',
        'placeholder_note_content': 'Enter note content...',
        'confirm_delete_note': 'Delete this note?',
        'note_saved': 'Note saved!',
        'type_note': 'Note',
        'type_appointment': 'Appointment',
        'label_note_type': 'Type',
        'notification_title': 'Notifications',
        'notification_today': 'Today',
        'notification_upcoming': 'Upcoming',
        'no_notifications': 'No new notifications',
        'title_edit_note_modal': 'Note / Appointment Details',
        'btn_update_note': 'Update',
        'btn_delete_note': 'Delete',
        'btn_close': 'Close',
        'btn_print_report_html': 'Print Preview (HTML)',
        'report_generated_by': 'Generated by',
        'label_view_by': 'View by',
        'label_time_filter': 'Time filter',
        'quick_filter_placeholder': '-- Quick Select --',
        'filter_today': 'Today',
        'filter_this_week': 'This Week',
        'filter_this_month': 'This Month',
        'filter_last_month': 'Last Month',
        'filter_this_year': 'This Year',
        'filter_last_year': 'Last Year',
        'btn_print_browser_action': 'Print (Browser)',
        'dashboard_status_overview': 'Status Overview',
        'search_placeholder': 'Search project, PO, client...',
        'filter_all_owners': '-- All Employers --',
        'filter_reset_title': 'Reset',
        'toggle_dark_mode': 'Toggle Dark Mode',
        'search_label': 'Search',
        'msg_login_required': 'You need to login.',
        'msg_no_permission': 'Permission denied.',
        'err_fill_all_fields': 'Please fill in all fields.',
        'err_email_format': 'Invalid email format.',
        'err_password_strength': 'Password must be at least 8 characters, including uppercase, lowercase, number and special character.',
        'err_password_mismatch': 'Passwords do not match.',
        'err_manager_create_admin': 'Manager cannot create Admin account.',
        'msg_user_added': '✅ User added.',
        'err_user_exists': '❌ Username or Email already exists.',
        'err_user_add_failed': '❌ Failed to add user.',
        'err_user_not_found': 'User not found.',
        'err_manager_edit_admin': 'Manager cannot edit Admin account.',
        'err_email_required': 'Email cannot be empty.',
        'err_email_used': 'This email is already in use.',
        'err_manager_promote_admin': 'Manager cannot promote to Admin.',
        'err_password_change_denied': 'You do not have permission to change password for this user.',
        'msg_password_updated': '✅ Password updated.',
        'msg_user_updated': '✅ User updated.',
        'err_user_update_failed': '❌ Failed to update user.',
        'err_delete_self': '❌ Cannot delete your own account.',
        'err_manager_delete_admin': 'Manager cannot delete Admin account.',
        'msg_user_deleted': '🗑️ User deleted.',
        'err_user_delete_failed': '❌ Failed to delete user.',
        'msg_login_allowed': '✅ Login allowed.',
        'err_login_status_update_failed': '❌ Failed to update login status.',
        'err_login_not_allowed': '❌ Account is not allowed to login.',
        'msg_login_success': '✅ Login successful!',
        'err_login_failed': '❌ Incorrect username or password.',
        'err_login_error': '❌ Login error. Please try again.',
        'msg_logout_success': '🚪 Logged out.',
        'err_current_password_incorrect': 'Current password is incorrect.',
        'msg_password_change_success': '✅ Password changed successfully.',
        'msg_backup_created': '✅ Backup created: ',
        'err_backup_failed': '❌ Backup creation failed.',
        'msg_restore_success': '♻️ Restore successful. Restarting application.',
        'err_restore_failed': '❌ Restore failed.',
        'msg_backup_deleted': '🗑️ Backup deleted.',
        'err_backup_delete_failed': '❌ Backup deletion failed.',
        'report_project_detail_title': 'PROJECT DETAIL',
        'report_combined_title': 'COMBINED PROJECT REPORT',
        'err_invalid_ids_list': 'Invalid IDs list',
        'err_ids_must_be_int': 'IDs must be integers',
        'err_projects_not_found': 'Projects not found',
        'err_no_project_selected': 'No project selected',
        'err_export_pdf_failed': 'PDF export failed',
        'err_path_not_exists': 'Path does not exist!',
        'msg_folder_opened': 'Folder opened.',
        'err_open_folder_failed': 'Cannot open folder: ',
        'label_time_est_short': 'Time Est.',
        'label_time_spent_short': 'Spent',
        'label_time_remain_short': 'Remain',
        'col_time_est_spent': 'Time Est.',
        'alert_connection_error': 'Connection error',
        'alert_enter_task_content': 'Please enter task content!',
        'alert_update_failed': 'Update failed',
        'kanban_doing': 'Doing',
        'kanban_done': 'Done',
        'kanban_new': 'New',
        'kanban_subtitle': 'Drag and drop to update task status',
        'kanban_title': 'Kanban',
        'btn_print_this_page': 'Print this page',
        'completed_at': 'Completed at',
    }
}

def get_lang():
    # Only Admin can change language, others default to 'en'
    if current_user.is_authenticated and current_user.role != 'admin':
        return 'en'
    
    # For admin or non-authenticated users, respect session lang or default to 'en'
    lang = session.get('lang') or 'en'
    if lang not in LANGS:
        lang = 'en'
    return lang

def t(key):
    lang = get_lang()
    return TRANSLATIONS.get(lang, {}).get(key, TRANSLATIONS['vi'].get(key, key))

# Role helper
ROLE_LEVEL = {'member': 10, 'secretary': 20, 'quotation': 30, 'leader': 40, 'manager': 50, 'admin': 60}

def min_role_required(min_role):
    def decorator(f):
        @wraps(f)
        def wrapper(*a, **kw):
            if not current_user.is_authenticated:
                flash("❌ Bạn cần đăng nhập.", "error")
                return redirect(url_for('auth.login'))
            
            # Special case: Quotation role can access edit_project if it's a quotation
            if current_user.role == 'quotation' and request.endpoint == 'projects.edit_project':
                project_id = kw.get('project_id')
                if project_id:
                    from app.models import Project
                    project = db.session.get(Project, project_id)
                    if project and project.status and project.status.startswith('Quotation'):
                         return f(*a, **kw)

            if ROLE_LEVEL.get(current_user.role, 0) < ROLE_LEVEL[min_role]:
                flash("❌ Không có quyền.", "error")
                return redirect(url_for('main.dashboard'))
            return f(*a, **kw)
        return wrapper
    return decorator

def is_valid_email(email):
    # Simple regex for email validation
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return re.match(pattern, email) is not None

def is_strong_password(password):
    # Min 8 chars, 1 uppercase, 1 lowercase, 1 digit, 1 special char
    if len(password) < 8:
        return False
    if not re.search(r'[A-Z]', password):
        return False
    if not re.search(r'[a-z]', password):
        return False
    if not re.search(r'\d', password):
        return False
    if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
        return False
    return True

def format_date(date_obj):
    if not date_obj:
        return '—'
    try:
        if isinstance(date_obj, datetime):
            date_obj = date_obj.date()
        if not isinstance(date_obj, date):
            return str(date_obj)
        # Universal format requested: Jan 02 (%b %d) -> Updated: Jan 02, 23 (%b %d, %y)
        return date_obj.strftime('%b %d, %y')
    except Exception:
        return str(date_obj)

def project_title(name):
    # Use title() to capitalize words, which handles underscores correctly (e.g. 123_abc -> 123_Abc)
    return (name or '').title()

def format_code(project):
    try:
        if not project:
            return "—"
            
        # Handle if project is passed as string (just the code)
        if isinstance(project, str):
            po = project.strip()
        else:
            # Assume it's a Project object
            po = (getattr(project, 'po_number', '') or "").strip()
        
        # Strategy: Find exactly 8 digits. 
        # If found, check if the surrounding characters are just "FGC", "-", spaces, etc.
        # This handles "FGC-12345678", "FGC 12345678", "12345678 (FGC)", etc.
        
        # 1. Look for 8 digit sequence
        match = re.search(r'(\d{8})', po)
        if match:
            digits = match.group(1)
            # 2. Check if the rest is just "FGC" related noise
            # Remove the digits from the original string
            remainder = po.replace(digits, "", 1) # replace only first occurrence
            
            # Check if remainder consists ONLY of FGC, fgc, spaces, dashes, underscores, brackets
            # using regex: (?i)^[\s\-_()\[\]FGC]*$
            if re.match(r'(?i)^[\s\-_()\[\]FGC]*$', remainder):
                return digits
                
        # Fallback: if existing logic (for simple cases) or just return original
        # (The above logic covers the "FGC-..." case and "12345678" case)
        
        return po or "PEI"
    except Exception as e:
        print(f"Error in format_code: {e}")
        return str(project) if project else "—"
