"""fix_calendar_note_and_project_question

Revision ID: 14410d864504
Revises: 55e13260f089
Create Date: 2026-01-03 11:00:14.756103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14410d864504'
down_revision = '55e13260f089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_note', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_note_date')
        batch_op.alter_column('date', new_column_name='note_date')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_symbol'), ['symbol'], unique=False)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_po_number'), ['po_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_po_number'))
        batch_op.drop_index(batch_op.f('ix_project_name'))

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_project_id'))
        batch_op.drop_index(batch_op.f('ix_history_date'))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_symbol'))
        batch_op.drop_index(batch_op.f('ix_client_name'))

    with op.batch_alter_table('calendar_note', schema=None) as batch_op:
        batch_op.alter_column('note_date', new_column_name='date')
        batch_op.create_index('ix_calendar_note_date', ['date'], unique=False)

    # ### end Alembic commands ###
