"""Add note column to project table

Revision ID: 32b4692e9f04
Revises: abcd1234addt
Create Date: 2026-03-17 20:47:24.853055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b4692e9f04'
down_revision = 'abcd1234addt'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Raw SQL execution with IF NOT EXISTS (PostgreSQL syntax)
    # Using fallback logic for SQLite (local dev)
    # Using text() to wrap raw SQL for SQLAlchemy execution
    if conn.engine.name == 'postgresql':
        op.execute(sa.text("ALTER TABLE project ADD COLUMN IF NOT EXISTS note TEXT"))
    else:
        inspector = sa.inspect(conn)
        columns = [c['name'] for c in inspector.get_columns('project')]
        if 'note' not in columns:
            with op.batch_alter_table('project', schema=None) as batch_op:
                batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('note')
    # ### end Alembic commands ###
