"""add note column to client

Revision ID: cddc9867caf5
Revises: 
Create Date: 2025-12-12 09:16:24.186474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddc9867caf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_client_po'), type_='unique')
        batch_op.create_unique_constraint('uq_client_po', ['client_id', 'po_number'])
        # batch_op.drop_column('client')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('uq_client_po', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_client_po'), ['client', 'po_number'])

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('note')

    # ### end Alembic commands ###
