"""Add question and source to project

Revision ID: f158158156e8
Revises: cddc9867caf5
Create Date: 2026-01-01 00:42:50.525854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f158158156e8'
down_revision = 'cddc9867caf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    if conn.engine.name == 'postgresql':
        op.execute(sa.text("ALTER TABLE project ADD COLUMN IF NOT EXISTS question TEXT"))
        op.execute(sa.text("ALTER TABLE project ADD COLUMN IF NOT EXISTS source VARCHAR(255)"))
    else:
        with op.batch_alter_table('project', schema=None) as batch_op:
            # For SQLite (local dev), we need to check columns first
            inspector = sa.inspect(conn)
            columns = [c['name'] for c in inspector.get_columns('project')]
            
            if 'question' not in columns:
                batch_op.add_column(sa.Column('question', sa.Text(), nullable=True))
            if 'source' not in columns:
                batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
